export const storeProducts = [
    {
    id:1,
    user : 'admin',
    name:'Основной запорный механизм Roto 801-1200',
    description : "Основной запорный механизм Roto 801-1200",
    price : 450,
    img :'img/osnovnojmah.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },

    {
    id:2,
    user : 'admin',
    name:'Основной запорный механизм Roto 1201-1600',
    description : "Основной запорный механизм Roto 1201-1600",
    price : 500,
    img:'img/osnovnojmah.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },

    {
    id:3,
    user : 'admin',
    name :'Основной запорный механизм Roto 1601-2000',
    description : "Основной запорный механизм Roto 1601-2000",
    price : 750,
    img: 'img/osnovnojmah.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    
    {
    id:4,
    user : 'admin',
    name:'Основной запорный механизм Roto 2001-2400 ',
    description : "Основной запорный механизм Roto 2001-2400",
    price : 850,
    img :'img/osnovnojmah.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    
    {
    id:5,
    user : 'admin',
    name:'Основной запор константа Roto 1001-1200',
    description : "Основной запор константа Roto 1001-1200",
    price : 750,
    img:'img/osn_meh_cons.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    
    {
    id:6,
    user : 'admin',
    name :'Основной запор константа Roto 1201-1400',
    description : "Основной запор константа Roto 1201-1400",
    price : 600,
    img: 'img/osn_meh_cons.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
{
    id:7,
    user : 'admin',
    name:'Основной запор константа Roto 1401-1600',
    description : "Основной запор константа Roto 1401-1600",
    price : 550,
    img:'img/osn_meh_cons.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:8,
    user : 'admin',
    name:'Планка опорная поворотно-откидная Roto',
    description : "Планка опорная поворотно-откидная Roto",
    price : 750,
    img:'img/Planka_otv_pov_otk_opornaya.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:9,
    user : 'admin',
    name:'Ножницы 9 Roto 411-600',
    description : "Ножницы 9 Roto 411-600",
    price : 450,
    img:'img/nozhnici_na_ramu.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:10,
    user : 'admin',
    name:'Ножницы 13 Roto 411-600',
    description : "Ножницы 13 Roto 411-600",
    price : 450,
    img:'img/nozhnici_na_ramu.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:11,
    user : 'admin',
    name:'Ножницы 9 Roto 601-800',
    description : "Ножницы 9 Roto 601-800",
    price : 500,
    img:'img/nozhnici_na_ramu.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:12,
    user : 'admin',
    name:'Ножницы 13 Roto 601-800',
    description : "Ножницы 13 Roto 601-800",
    price : 500,
    img:'img/nozhnici_na_ramu.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:13,
    user : 'admin',
    name:'Петля верхняя на раму Roto',
    description : "Петля верхняя на раму Roto",
    price : 130,
    img:'img/petlya_na_ramu_verh.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:14,
    user : 'admin',
    name:'Петля нижняя комплект Roto ',
    description : "Петля нижняя комплект на створку и на раму Roto",
    price : 230,
    img:'img/nizhnyayapetlya.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:15,
    user : 'admin',
    name:'Угловой переключатель Roto',
    description : "Угловой переключатель Roto",
    price : 230,
    img:'img/uglovoj_pereklucatel.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:16,
    user : 'admin',
    name:'Переключатель от ножниц Roto 400',
    description : "Переключатель от ножниц Roto 400",
    price : 150,
    img:'img/Perekluchatel_ugl_verhn_ot_nozhn.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:17,
    user : 'admin',
    name:'Переключатель от ножниц Roto 600',
    description : "Переключатель от ножниц Roto 600",
    price : 200,
    img:'img/Perekluchatel_ugl_verhn_ot_nozhn.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:18,
    user : 'admin',
    name:'Удлинитель Roto 400',
    description : "Удлинитель Roto 400",
    price : 300,
    img:'img/Udlinitel_zapora_400.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:19,
    user : 'admin',
    name:'Удлинитель Roto 200',
    description : "Удлинитель Roto 200",
    price : 270,
    img:'img/Udlinitel_zapora_200.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:20,
    user : 'admin',
    name:'Верхняя петля поворотная Roto',
    description : "Верхняя петля поворотная Roto",
    price : 300,
    img:'img/Petlya_na_stvorku_verh.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:21,
    user : 'admin',
    name:'Декоративная накладка нижняя Roto',
    description : "Декоративная накладка нижняя Roto",
    price : 20,
    img:'img/nakladki-petli-roto-800x600.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:22,
    user : 'admin',
    name:'Декоративная накладка верхняя Roto',
    description : "Декоративная накладка верхняя Roto",
    price : 20,
    img:'img/nakladki-petli-roto-800x600.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:23,
    user : 'admin',
    name:'Ответная планка 13 Roto',
    description : "Ответная планка 13 Roto",
    price : 40,
    img:'./img/planka_otv13.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:24,
    user : 'admin',
    name:'Ответная планка 9 Roto',
    description : "Ответная планка 9 Roto",
    price : 40,
    img:'img/Planka_otv9.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:25,
    user : 'admin',
    name:'Основной запор Siegenia 801-1200',
    description : "Основной запор Siegenia 801-1200",
    price : 320,
    img:'img/Zapor_osn_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:26,
    user : 'admin',
    name:'Основной запор Siegenia 1201-1600',
    description : "Основной запор Siegenia 1201-1600",
    price : 400,
    img:'img/Zapor_osn_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:27,
    user : 'admin',
    name:'Основной запор Siegenia 1601-2000',
    description : "Основной запор Siegenia 1601-2000",
    price : 500,
    img:'img/Zapor_osn_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:28,
    user : 'admin',
    name:'Нижний шпингалет поворотно-откидной Siegenia',
    description : "Нижний шпингалет поворотно-откидной Siegenia",
    price : 270,
    img:'img/Shpingalet_nizhnii_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:29,
    user : 'admin',
    name:'Ножницы Siegenia 290-620',
    description : "Ножницы Siegenia 290-620",
    price : 300,
    img:'img/Nozhnici_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:30,
    user : 'admin',
    name:'Ножницы Siegenia 571-800',
    description : "Ножницы Siegenia 571-800",
    price : 450,
    img :'img/Nozhnici_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:31,
    user : 'admin',
    name:'Угловой переключатель Siegenia',
    description : "Угловой переключатель Siegenia",
    price : 170,
    img:'img/Perekluchatel_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:32,
    user : 'admin',
    name :'Запор средний Siegenia 1200-1400',
    description : "Запор средний Siegenia 1200-1400",
    price : 480,
    img: 'img/Zapor_srednii_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },    
    {
    id:33,
    user : 'admin',
    name:'Запор средний Siegenia 1400-1600',
    description : "Запор средний Siegenia 1400-1600",
    price : 560,
    img: 'img/Zapor_srednii_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },    
    {
    id:34,
    user : 'admin',
    name:'Запор средний Siegenia 1600-2400',
    description : "Запор средний Siegenia 1600-2400",
    price : 750,
    img: 'img/Zapor_srednii_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },    
    {
    id:35,
    user : 'admin',
    name :'Петля верхняя Siegenia',
    description : "Петля верхняя Siegenia",
    price : 150,
    img: 'img/petlya_verh_rama_Siegenia.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:36,
    user : 'admin',
    name:'Петля нижняя Siegenia',
    description : "Петля нижняя Siegenia",
    price : 250,
    img:'img/Petlya_nizhn_ramnaya_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:37,
    user : 'admin',
    name:'Декоративная накладка верхняя Siegenia',
    description : "Декоративная накладка верхняя Siegenia",
    price : 20,
    img:'img/decor_siegenia.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:38,
    user : 'admin',
    name:'Декоративная накладка нижняя Siegenia',
    description : "Декоративная накладка нижняя Siegenia",
    price : 20,
    img:'img/decor_siegenia.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:39,
    user : 'admin',
    name:'Ответная планка 9/20 Siegenia',
    description : "Ответная планка 9/20 Siegenia",
    price : 30,
    img:'img/otvet_plan9.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:40,
    user : 'admin',
    name:'Ответная планка 13/20 Siegenia',
    description : "Ответная планка 13/20 Siegenia",
    price : 30,
    img:'img/otvet_plan9.jpg',
    company:'Siegenia',   
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:41,
    user : 'admin',
    name:'Петля верхняя (ухо) 9/20 Siegenia',
    description : "Петля верхняя (ухо) 9/20 Siegenia",
    price : 100,
    img:'img/Petlya_verh_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:42,
    user : 'admin',
    name:'Петля верхняя (ухо) 13/20 Siegenia',
    description : "Петля верхняя (ухо) 13/20 Siegenia",
    price : 100,
    img:'img/Petlya_verh_SIEGENIA.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:43,
    user : 'admin',
    name:'Ответная планка поворотно-откидная 13/20 Siegenia',
    description : "Ответная планка поворотно-откидная 13/20 Siegenia",
    price : 50,
    img:'img/Planka_otvetnaya_povotk_SIEGENIA13.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:44,
    user : 'admin',
    name:'Ответная планка поворотно-откидная 9/20 Siegenia',
    description : "Ответная планка поворотно-откидная 9/20 Siegenia",
    price : 50,
    img:'img/Planka_otvetnaya_povotk_SIEGENIA13.jpg',
    company:'Siegenia',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:45,
    user : 'admin',
    name:'Гребенка металлическая',
    description : "Гребенка металлическая",
    price : 120,
    img:'img/grebenka-metall.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:46,
    user : 'admin',
    name:'Балконная защёлка механическая',
    description : "Балконная защёлка механическая",
    price : 120,
    img:'img/Balkonnaya_zaschelka_9_mm.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:47,
    user : 'admin',
    name:'Балконная защёлка магнитная',
    description : "Балконная защёлка магнитная",
    price : 100,
    img:'img/zacelka_magnit.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:48,
    user : 'admin',
    name:'Дополнительный прижим внешний',
    description : "Дополнительный прижим внешний",
    price : 120,
    img:'img/dop_priszim.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:49,
    user : 'admin',
    name:'Ручка металлическая',
    description : "Ручка металлическая",
    price : 120,
    img:'img/Ruchka.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:50,
    user : 'admin',
    name:'Ручка Roto lain',
    description : "Ручка Roto lain",
    price : 260,
    img:'img/rucka_roto.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:51,
    user : 'admin',
    name:'Ручка Roto sving',
    description : "Ручка Roto sving",
    price : 280,
    img:'img/ROTO_SWING.jpg',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:52,
    user : 'admin',
    name:'Уплотнитель для пластиковых окон',
    description : "Уплотнитель для пластиковых окон.Уплотнитель продается по метражу. Разные производители. KBE 228 Rexay",
    price : 20,
    img:'img/uplotnitel.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:53,
    user : 'admin',
    name:'Ручка курильщика металическая',
    description : "Ручка курильщика металическая",
    price : 50,
    img:'img/rucka_kurilscika.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:54,
    user : 'admin',
    name:'Москитная сетка стандарт (под заказ)',
    description : "Москитная сетка стандарт (под заказ)",
    price : 850,
    img:'img/ms.png',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:55,
    user : 'admin',
    name:'Москитная сетка антикошка (под заказ)',
    description : "Москитная сетка антикошка (под заказ)",
    price : 1250,
    img:'img/ms_anti_cat.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:56,
    user : 'admin',
    name:'Москитная сетка антипыль (под заказ)',
    description : "Москитная сетка антипыль (под заказ)",
    price : 1500,
    img:'img/ms_antipyl.jpg',
    company:'Other',
    inCart: false,
    count : 0,
    total : 0
    },
    {
    id:57,
    user : 'admin',
    name:'Термо короб для теплого алюминия (под заказ)',
    description : "Термо короб для теплого алюминия (под заказ)",
    price : 750,
    img:'img/termo_corob.png',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
    }    
];

export const detailProduct ={
    id:1,
    user : 'admin',
    name:'Roto ножницы 350-600',
    description : "Ножницы для фурнитуры Roto NT",
    price : 450,
    img :'img/ms.png',
    company:'Roto',
    inCart: false,
    count : 0,
    total : 0
}
